package chip

type ErrorCode string

const (
	UNKNOWN_PAYMENT_METHOD                          ErrorCode = "unknown_payment_method"
	INVALID_CARD_NUMBER                             ErrorCode = "invalid_card_number"
	INVALID_EXPIRES                                 ErrorCode = "invalid_expires"
	NO_MATCHING_TERMINAL                            ErrorCode = "no_matching_terminal"
	BLACKLISTED_TX                                  ErrorCode = "blacklisted_tx"
	TIMEOUT_3DS_ENROLLMENT_CHECK                    ErrorCode = "timeout_3ds_enrollment_check"
	TIMEOUT_ACQUIRER_STATUS_CHECK                   ErrorCode = "timeout_acquirer_status_check"
	VALIDATION_CARD_DETAILS_MISSING                 ErrorCode = "validation_card_details_missing"
	VALIDATION_CVC_NOT_PROVIDED                     ErrorCode = "validation_cvc_not_provided"
	VALIDATION_CARDHOLDER_NAME_NOT_PROVIDED         ErrorCode = "validation_cardholder_name_not_provided"
	VALIDATION_EXPIRES_NOT_PROVIDED                 ErrorCode = "validation_expires_not_provided"
	VALIDATION_CVC_TOO_LONG                         ErrorCode = "validation_cvc_too_long"
	VALIDATION_CARDHOLDER_NAME_TOO_LONG             ErrorCode = "validation_cardholder_name_too_long"
	VALIDATION_CARD_NUMBER_TOO_LONG                 ErrorCode = "validation_card_number_too_long"
	VALIDATION_EXPIRES_TOO_LONG                     ErrorCode = "valiadtion_expires_too_long"
	THREE_DS_AUTHENTICATION_FAILED                  ErrorCode = "3ds_authentication_failed"
	VALIDATION_CVC_INVALID                          ErrorCode = "validation_cvc_invalid"
	VALIDATION_CARDHOLDER_NAME_INVALID              ErrorCode = "validation_cardholder_name_invalid"
	VALIDATION_CARD_NUMBER_INVALID                  ErrorCode = "validation_card_number_invalid"
	VALIDATION_EXPIRES_INVALID                      ErrorCode = "validation_expires_invalid"
	ACQUIRER_CONNECTION_ERROR                       ErrorCode = "acquirer_connection_error"
	BLACKLISTED_TX_ISSUING_COUNTRY                  ErrorCode = "blacklisted_tx_issuing_country"
	S2S_NOT_SUPPORTED                               ErrorCode = "s2s_not_supported"
	TIMEOUT                                         ErrorCode = "timeout"
	GENERAL_TRANSACTION_ERROR                       ErrorCode = "general_transaction_error"
	ANTIFRAUD_GENERAL                               ErrorCode = "antifraud_general"
	ACQUIRER_INTERNAL_ERROR                         ErrorCode = "acquirer_internal_error"
	EXCEEDS_FREQUENCY_LIMIT                         ErrorCode = "exceeds_frequency_limit"
	INSUFFICIENT_FUNDS                              ErrorCode = "insufficient_funds"
	PURCHASE_ALREADY_PAID_FOR                       ErrorCode = "purchase_already_paid_for"
	ISSUER_NOT_AVAILABLE                            ErrorCode = "issuer_not_available"
	DO_NOT_HONOUR                                   ErrorCode = "do_not_honour"
	EXCEEDS_WITHDRAWAL_LIMIT                        ErrorCode = "exceeds_withdrawal_limit"
	EXCEEDED_ACCOUNT_LIMIT                          ErrorCode = "exceeded_account_limit"
	EXPIRED_CARD                                    ErrorCode = "expired_card"
	BLACKLISTED_TX_RISK_SCORE                       ErrorCode = "blacklisted_tx_risk_score"
	TRANSACTION_NOT_SUPPORTED_OR_NOT_VALID_FOR_CARD ErrorCode = "transaction_not_supported_or_not_valid_for_card"
	EXCEEDED_ACQUIRER_REFUND_AMOUNT                 ErrorCode = "exceeded_acquirer_refund_amount"
	TRANSACTION_NOT_PERMITTED_ON_TERMINAL           ErrorCode = "transaction_not_permitted_on_terminal"
	ACQUIRER_CONFIGURATION_ERROR                    ErrorCode = "acquirer_configuration_error"
	TRANSACTION_NOT_PERMITTED_TO_CARDHOLDER         ErrorCode = "transaction_not_permitted_to_cardholder"
	INVALID_ISSUER_NUMBER                           ErrorCode = "invalid_issuer_number"
	RESTRICTED_CARD                                 ErrorCode = "restricted_card"
	MERCHANT_RESPONSE_TIMEOUT                       ErrorCode = "merchant_response_timeout"
	RECONCILE_ERROR                                 ErrorCode = "reconcile_error"
	LOST_CARD                                       ErrorCode = "lost_card"
	STOLEN_CARD                                     ErrorCode = "stolen_card"
	INVALID_AMOUNT                                  ErrorCode = "invalid_amount"
	RE_ENTER_TRANSACTION                            ErrorCode = "re_enter_transaction"
	SECURITY_VIOLATION                              ErrorCode = "security_violation"
	PARTIAL_FORBIDDEN                               ErrorCode = "partial_forbidden"
	SUSPECTED_FRAUD                                 ErrorCode = "suspected_fraud"
	ACQUIRER_ROUTING_ERROR                          ErrorCode = "acquirer_routing_error"
	PAYMENT_REJECTED_OTHER_REASON                   ErrorCode = "payment_rejected_other_reason"
	AUTHORIZATION_FAILED                            ErrorCode = "authorization_failed"
	ACQUIRER_ERROR_CS                               ErrorCode = "acquirer_error_cs"
	DECLINE_IRREGULAR_TRANSACTION_PATTERN           ErrorCode = "decline_irregular_transaction_pattern"
	INVALID_CARD_DATA                               ErrorCode = "invalid_card_data"
	EXCEEDED_TERMINAL_LIMIT                         ErrorCode = "exceeded_terminal_limit"
	RECURRING_TOKEN_EXPIRED                         ErrorCode = "recurring_token_expired"
	SOFT_DECLINE_CONTACT_SUPPORT                    ErrorCode = "soft_decline_contact_support"
	PAYMENT_METHOD_DETAILS_MISSING                  ErrorCode = "payment_method_details_missing"
	VALIDATION_PHONE_INVALID                        ErrorCode = "validation_phone_invalid"
	VALIDATION_ADDRESS_INVALID                      ErrorCode = "validation_address_invalid"
)

type Error struct {
	Description string    `json:"description"`
	Code        ErrorCode `json:"code"`
	Message     string    `json:"message"`
}
